//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRateApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeRateApi.Resources.CommandsResources", typeof(CommandsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏦 NBU - National Bank of Ukraine
        ///🏦 PB - PrivatBank.
        /// </summary>
        public static string AboutBank {
            get {
                return ResourceManager.GetString("AboutBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ {0}.
        /// </summary>
        public static string CheckMark {
            get {
                return ResourceManager.GetString("CheckMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Commands*
        ///
        ////start - Start conquering humanity
        ////tutorial - Instructions on how to work with me
        ////currencies - All currencies that I support
        ////setcurrency - Select favorite currencies
        ////settings - Personal bot settings.
        /// </summary>
        public static string CommandsList {
            get {
                return ResourceManager.GetString("CommandsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to favorites.
        /// </summary>
        public static string CurrencyAdded {
            get {
                return ResourceManager.GetString("CurrencyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💱 {0}.
        /// </summary>
        public static string CurrencyExchangeCode {
            get {
                return ResourceManager.GetString("CurrencyExchangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed from favorites.
        /// </summary>
        public static string CurrencyRemoved {
            get {
                return ResourceManager.GetString("CurrencyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, nothing was found for this date.
        /// </summary>
        public static string NoExchangeRateFound {
            get {
                return ResourceManager.GetString("NoExchangeRateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any currencies to your favorites. This can be done with the 👉 /setcurrency command.
        /// </summary>
        public static string NoSelectedRates {
            get {
                return ResourceManager.GetString("NoSelectedRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Unfortunately it is not possible to get data on the following currencies: _.
        /// </summary>
        public static string NotFoundExchangeRates {
            get {
                return ResourceManager.GetString("NotFoundExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBU purchase rate: *{0}*.
        /// </summary>
        public static string PurchaseRateNBU {
            get {
                return ResourceManager.GetString("PurchaseRateNBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB purchase rate: *{0}*.
        /// </summary>
        public static string PurchaseRatePB {
            get {
                return ResourceManager.GetString("PurchaseRatePB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBU selling rate: *{0}*.
        /// </summary>
        public static string SaleRateNBU {
            get {
                return ResourceManager.GetString("SaleRateNBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB sales rate: *{0}*.
        /// </summary>
        public static string SaleRatePB {
            get {
                return ResourceManager.GetString("SaleRatePB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or remove currency from favourites.
        /// </summary>
        public static string SetCurrencyAbout {
            get {
                return ResourceManager.GetString("SetCurrencyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a bot that returns the exchange rate on the selected date (in relation to *UAH*) for the last 4 years
        ///
        ///*How to see the exchange rate?*
        ///1. Use the /setcurrency command to select a currency.
        ///2. Enter the date in the format _month/day/year_
        ///
        ///*Also have a look at* 👉 /help.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!.
        /// </summary>
        public static string WelcomeWithoutUsername {
            get {
                return ResourceManager.GetString("WelcomeWithoutUsername", resourceCulture);
            }
        }
    }
}
